<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>KeDungeon</AssemblyName>
    <RootNamespace>KeDungeon</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../KhaozEngine.Dungeon/KhaozEngine.Dungeon.csproj" />
    <ProjectReference Include="../../KhaozEngine.Imaging/KhaozEngine.Imaging.csproj" />
    <ProjectReference Include="../../KhaozEngine.Navigation/KhaozEngine.Navigation.csproj" />
  </ItemGroup>
</Project>
