<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="assets/icon.png" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets/props/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets/character/**" CopyToOutputDirectory="PreserveNewest" />
    <None Include="assets/buildings/**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../KhaozEngine.Windowing/KhaozEngine.Windowing.csproj" />
    <ProjectReference Include="../KhaozEngine.Render2D/KhaozEngine.Render2D.csproj" />
    <ProjectReference Include="../KhaozEngine.Gui/KhaozEngine.Gui.csproj" />
    <ProjectReference Include="../KhaozEngine.Audio/KhaozEngine.Audio.csproj" />
    <ProjectReference Include="../KhaozEngine.Game/KhaozEngine.Game.csproj" />
    <ProjectReference Include="../KhaozEngine.Game.Render3D/KhaozEngine.Game.Render3D.csproj" />
    <ProjectReference Include="../KhaozEngine.Render3D/KhaozEngine.Render3D.csproj" />
    <ProjectReference Include="../KhaozEngine.Terrain/KhaozEngine.Terrain.csproj" />
    <ProjectReference Include="../KhaozEngine.Terrain.Render3D/KhaozEngine.Terrain.Render3D.csproj" />
    <ProjectReference Include="../KhaozEngine.Physics/KhaozEngine.Physics.csproj" />
    <ProjectReference Include="../KhaozEngine.Physics.Bepu/KhaozEngine.Physics.Bepu.csproj" />
    <ProjectReference Include="../KhaozEngine.NetWorld/KhaozEngine.NetWorld.csproj" />
    <ProjectReference Include="../KhaozEngine.Locomotion/KhaozEngine.Locomotion.csproj" />
    <ProjectReference Include="../KhaozEngine.Netcode.LiteNetLib/KhaozEngine.Netcode.LiteNetLib.csproj" />
    <ProjectReference Include="../KhaozEngine.Simulation/KhaozEngine.Simulation.csproj" />
  </ItemGroup>
</Project>
