<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>KhaozEngine.Ecs</PackageId>
    <Description>Game-agnostic struct-based archetype ECS: versioned entities, ref access, ForEach queries, command buffer, resources, systems.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>1.4.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
