using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization.Metadata;
using KhaozEngine.Serialization;

namespace KhaozEngine.Ecs;

/// <summary>
/// Saves and loads a <see cref="World"/> (entities + components + id-allocator state) as JSON.
/// Construct it with the component types your game uses (or scan an assembly). Entities are restored
/// at their exact id and version so <see cref="Entity"/>-typed component fields survive the round-trip.
/// Resources and systems are not serialized.
///
/// <para><b>NativeAOT.</b> Register the component set through the generic seam - <see cref="Create"/> then
/// <see cref="Builder.Add{T}"/> - so the load path can rebuild each component column without reflection, and pass
/// JSON options backed by a source-generated <see cref="System.Text.Json.Serialization.JsonSerializerContext"/> for
/// the component structs (the envelope itself is source-generated by the engine). The non-generic <see cref="Type"/>
/// constructors and <see cref="FromAssemblyOf{T}"/> stay reflection-based and are JIT-only.</para>
/// </summary>
public sealed class WorldSerializer
{
    /// <summary>Starts a generic, NativeAOT-safe registration. Chain <see cref="Builder.Add{T}"/> for each component
    /// type, then <see cref="Builder.Build"/>. Each <c>Add&lt;T&gt;()</c> records a reflection-free column factory, so a
    /// freshly loaded world rebuilds its columns without <c>Type.MakeGenericType</c>.</summary>
    public static Builder Create() => new();

    /// <summary>Fluent, generic component registration for <see cref="WorldSerializer"/>. Each <see cref="Add{T}"/>
    /// closes over <c>() =&gt; new Column&lt;T&gt;()</c> (via the reflection-free column-factory table), so the built
    /// serializer's load path is NativeAOT-safe.</summary>
    public sealed class Builder
    {
        private readonly List<Type> _types = new();

        /// <summary>Registers component type <typeparamref name="T"/> (a <c>struct</c> implementing
        /// <see cref="IComponent"/>). Reflection-free, so it is safe under NativeAOT.</summary>
        public Builder Add<T>() where T : struct, IComponent
        {
            ComponentColumnFactory.Register<T>();
            _types.Add(typeof(T));
            return this;
        }

        /// <summary>Builds the serializer over the registered component set. <paramref name="options"/> defaults to
        /// <see cref="JsonDefaults.IncludeFields"/>; under NativeAOT pass options whose
        /// <see cref="JsonSerializerOptions.TypeInfoResolver"/> is a source-generated context covering the component
        /// structs.</summary>
        public WorldSerializer Build(JsonSerializerOptions? options = null) => new(_types, options);
    }

    /// <summary>The save <c>FormatVersion</c> this build writes and is the newest it can read.</summary>
    public const int CurrentFormatVersion = 1;

    // Document-level upgrade hooks, keyed by the version they upgrade FROM (ascending). A migration
    // registered at N takes a document at version N and returns it at version N+1. Load applies every
    // migration from the save's version up to CurrentFormatVersion before deserializing.
    private static readonly SortedDictionary<int, Func<JsonObject, JsonObject>> _migrations = new();

    /// <summary>
    /// Registers a document-level upgrade from <paramref name="fromVersion"/> to <paramref name="fromVersion"/>+1.
    /// On <see cref="Load(string)"/> of an older save, registered migrations run in ascending order to bring the
    /// document up to <see cref="CurrentFormatVersion"/> before it is deserialized. The hook receives and returns
    /// the raw <see cref="JsonObject"/> save document.
    /// </summary>
    public static void RegisterMigration(int fromVersion, Func<JsonObject, JsonObject> upgrade)
        => _migrations[fromVersion] = upgrade ?? throw new ArgumentNullException(nameof(upgrade));

    // Resolves the persistence key for a component type: its [ComponentId] if present, else Type.FullName.
    private static string KeyFor(Type t) => t.GetCustomAttribute<ComponentIdAttribute>()?.Id ?? t.FullName!;

    private readonly Dictionary<string, Type> _byName = new();
    private readonly JsonSerializerOptions _options;

    /// <param name="componentTypes">Each must be a <c>struct</c> implementing <see cref="IComponent"/>.</param>
    public WorldSerializer(params Type[] componentTypes) : this(componentTypes, null) { }

    /// <param name="componentTypes">Each must be a <c>struct</c> implementing <see cref="IComponent"/>.</param>
    /// <param name="options">Optional JSON options; defaults to a reflection-based <c>IncludeFields = true</c> resolver
    /// (JIT). Under NativeAOT pass options whose <see cref="JsonSerializerOptions.TypeInfoResolver"/> is a
    /// source-generated context covering the component structs. Add converters here for value types that don't
    /// round-trip by default (e.g. a struct serialized via a custom JsonConverter).</param>
    public WorldSerializer(IEnumerable<Type> componentTypes, JsonSerializerOptions? options)
    {
        _options = options ?? ReflectionFallbackOptions();
        foreach (Type t in componentTypes)
        {
            if (!t.IsValueType || t.IsAbstract || !typeof(IComponent).IsAssignableFrom(t))
                throw new ArgumentException($"{t.FullName} is not a struct implementing IComponent.");
            string key = KeyFor(t);
            if (_byName.TryGetValue(key, out Type? existing) && existing != t)
                throw new ArgumentException(
                    $"Duplicate component key '{key}': both {existing.FullName} and {t.FullName} resolve to the same key. " +
                    $"Assign unique [ComponentId] values or use distinct type names.");
            _byName[key] = t;
        }
        // The built-in Parent component lives in the engine assembly, so callers' type lists/scans
        // won't include it; auto-register so hierarchies serialize.
        _byName[KeyFor(typeof(Parent))] = typeof(Parent);
    }

    // JIT default when the caller supplies no options: a reflection-based resolver so GetTypeInfo(componentType) works
    // without a source-generated context. RuntimeFeature.IsDynamicCodeSupported is a false constant under NativeAOT, so
    // ILC removes the reflection-default construction and emits no trim/AOT warning; an AOT consumer that reaches this
    // (default ctor / FromAssemblyOf) gets an actionable throw instead, and should pass source-generated options.
    private static JsonSerializerOptions ReflectionFallbackOptions()
    {
        if (!RuntimeFeature.IsDynamicCodeSupported)
            throw new NotSupportedException(
                "WorldSerializer needs JSON options backed by a source-generated resolver under NativeAOT. " +
                "Pass them to WorldSerializer.Create().Build(options) (or the Type[] constructor's options parameter).");
        return BuildReflectionDefaultOptions();
    }

    [RequiresDynamicCode("Builds a reflection-based JSON resolver; pass source-generated options under NativeAOT.")]
    [RequiresUnreferencedCode("Builds a reflection-based JSON resolver; pass source-generated options under NativeAOT.")]
    private static JsonSerializerOptions BuildReflectionDefaultOptions() =>
        new() { IncludeFields = true, TypeInfoResolver = new DefaultJsonTypeInfoResolver() };

    /// <summary>Builds a serializer from every <c>struct : IComponent</c> in <typeparamref name="T"/>'s assembly.
    /// Reflection-based type discovery, so it is JIT-only. Under NativeAOT use <see cref="Create"/> +
    /// <see cref="Builder.Add{T}"/> to register the component set explicitly.</summary>
    [RequiresUnreferencedCode("Discovers component types via Assembly.GetTypes(); use WorldSerializer.Create().Add<T>() under NativeAOT.")]
    public static WorldSerializer FromAssemblyOf<T>(JsonSerializerOptions? options = null)
    {
        var types = typeof(T).Assembly.GetTypes()
            .Where(t => t.IsValueType && !t.IsAbstract && typeof(IComponent).IsAssignableFrom(t));
        return new WorldSerializer(types, options);
    }

    /// <summary>Serializes the world to a JSON string.</summary>
    public string Save(World world)
    {
        var doc = new SaveDoc
        {
            NextId = world.SaveNextId,
            FreeIds = world.SaveFreeSlots.Select(s => new FreeSlot { Id = s.id, Version = s.version }).ToList(),
        };
        ComponentRegistry reg = world.Registry;
        foreach (Archetype arch in world.SaveArchetypes)
        {
            for (int row = 0; row < arch.Count; row++)
            {
                Entity e = arch.Entities[row];
                var ed = new EntityDoc { Id = e.Id, Version = e.Version };
                foreach (int tid in arch.TypeIds)
                {
                    Type t = reg.TypeOf(tid);
                    object value = reg.IsTag(tid)
                        ? reg.TagInstance(tid)
                        : arch.Columns[tid].GetBoxed(row);
                    // JsonTypeInfo overload (not the reflection Type overload): NativeAOT-safe when _options carries a
                    // source-generated resolver for the component structs. Under JIT, GetTypeInfo returns reflection info.
                    ed.Components[KeyFor(t)] = JsonSerializer.SerializeToElement(value, _options.GetTypeInfo(t));
                }
                doc.Entities.Add(ed);
            }
        }
        // The envelope (entities + allocator state) is serialized by the engine's source-generated context, so it
        // needs no reflection. Component values are already embedded as raw JsonElement, so this is byte-identical to
        // serializing the whole document in one reflection pass.
        return JsonSerializer.Serialize(doc, WorldSaveJsonContext.Default.SaveDoc);
    }

    /// <summary>Deserializes a world from a JSON string.</summary>
    public World Load(string json)
    {
        if (Jsonc.ParseNode(json) is not JsonObject root)
            throw new InvalidOperationException("Empty or invalid save document.");

        // Read the version BEFORE deserializing so a future save is rejected, not mis-read. A missing
        // FormatVersion is treated as version 1: pre-existing saves always wrote 1, and that is the
        // lowest known version.
        int found = root.TryGetPropertyValue("FormatVersion", out JsonNode? fv) && fv is not null
            ? fv.GetValue<int>()
            : CurrentFormatVersion;

        if (found > CurrentFormatVersion)
            throw new UnsupportedSaveVersionException(found, CurrentFormatVersion);

        // Older save: bring it up to the current version with any registered migrations (ascending).
        for (int v = found; v < CurrentFormatVersion; v++)
        {
            if (!_migrations.TryGetValue(v, out Func<JsonObject, JsonObject>? upgrade))
                throw new InvalidOperationException(
                    $"No migration registered to upgrade save FormatVersion {v} to {v + 1}.");
            root = upgrade(root);
            root["FormatVersion"] = v + 1;
        }

        // Envelope deserialized by the engine's source-generated context (reflection-free); component values below use
        // the JsonTypeInfo overload against _options so a source-generated resolver keeps them NativeAOT-safe too.
        SaveDoc doc = root.Deserialize(WorldSaveJsonContext.Default.SaveDoc)
            ?? throw new InvalidOperationException("Empty or invalid save document.");
        var world = new World();
        foreach (EntityDoc ed in doc.Entities)
        {
            Entity e = world.CreateAt(ed.Id, ed.Version);
            foreach (var (name, element) in ed.Components)
            {
                if (!_byName.TryGetValue(name, out Type? t))
                    throw new InvalidOperationException(
                        $"Unknown component type '{name}' on load. Register it with the WorldSerializer.");
                object value = JsonSerializer.Deserialize(element, _options.GetTypeInfo(t))!;
                world.SetByType(e, t, value);
            }
        }
        world.RestoreAllocator(doc.NextId, doc.FreeIds.Select(f => (f.Id, f.Version)));
        world.RebuildHierarchyIndex();
        return world;
    }

    /// <summary>Serializes the world to a stream (UTF-8 text).</summary>
    public void Save(World world, Stream stream)
    {
        using var w = new StreamWriter(stream, leaveOpen: true);
        w.Write(Save(world));
    }

    /// <summary>Deserializes a world from a stream (UTF-8 text).</summary>
    public World Load(Stream stream)
    {
        using var r = new StreamReader(stream, leaveOpen: true);
        return Load(r.ReadToEnd());
    }

    // Internal (not private) so the source-generated WorldSaveJsonContext can reference them. The JSON shape is the
    // save format - do not reorder members without a FormatVersion bump + migration.
    internal sealed class SaveDoc
    {
        public int FormatVersion { get; set; } = CurrentFormatVersion;
        public int NextId { get; set; }
        public List<FreeSlot> FreeIds { get; set; } = new();
        public List<EntityDoc> Entities { get; set; } = new();
    }

    internal sealed class FreeSlot { public int Id { get; set; } public uint Version { get; set; } }

    internal sealed class EntityDoc
    {
        public int Id { get; set; }
        public uint Version { get; set; }
        public Dictionary<string, JsonElement> Components { get; set; } = new();
    }
}
