<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <AssemblyName>PixelLabSheetAssembler</AssemblyName>
    <RootNamespace>PixelLabSheetAssembler</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" />
  </ItemGroup>
</Project>
