<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
    <RootNamespace>KhaozEngine.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../KhaozEngine.TileWorld.Netcode/KhaozEngine.TileWorld.Netcode.csproj" />
    <ProjectReference Include="../KhaozEngine.TileWorld/KhaozEngine.TileWorld.csproj" />
    <ProjectReference Include="../KhaozEngine.Netcode/KhaozEngine.Netcode.csproj" />
    <ProjectReference Include="../KhaozEngine.Replication/KhaozEngine.Replication.csproj" />
    <ProjectReference Include="../KhaozEngine.Sharding/KhaozEngine.Sharding.csproj" />
    <ProjectReference Include="../KhaozEngine.Simulation/KhaozEngine.Simulation.csproj" />
    <ProjectReference Include="../KhaozEngine.WorldStore/KhaozEngine.WorldStore.csproj" />
    <ProjectReference Include="../KhaozEngine.WorldStore.Sqlite/KhaozEngine.WorldStore.Sqlite.csproj" />
  </ItemGroup>
</Project>
